### ISSUE TITLE
Error produced when creating a gym.

### ISSUE THREAD

**Issue by HackuJacku** [NickImpact/Bidoof-Unleashed#3]
When running '/bu3 addgym name:Rock w:3' produces an error in conosle:

**Logs:**
Error produced: https://pastebin.com/raw/ZMJJEAG1
BU3 Startup Logs: https://pastebin.com/raw/eZPsVfxb

**Versions:**
BU3: Bidoof_Unleashed-S7.1.0-0.13.4-BETA
Impactor: Impactor-S7.1.0-1.4.0
SF: spongeforge-1.12.2-2705-7.1.0-BETA-3361

**Comment by NickImpact** [comment]
Looks like that error just needs better handling, but normally you’d receive a warning and the command wouldn’t complete because some needed details were missing. I’ll look into making this restriction a lot less harsh and go from there
